### ISSUE TITLE
Make code multi-threaded

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/iso-ics-codes-scripts#2]
Because scraping takes time, we should make this multi-threaded and display progress. The threading model should use the publisher / consumer model. 

The initial scrape of the top level page will indicate how many fields there are. Put these into a central Set/Array that is shared amongst threads.

Once we have this, then can start multiple threads to consume from this set, and then push additional fetch URLs to the shared array. 

Each successful fetch should immediately serialize the JSON to disk to ensure that partial progress is not lost. 

The command line to start this process should take an additional option to determine number of threads to start.

**Comment by andrew2net** [comment]
Made the script multi-thread. Then I set thread number more than 4 I got `connection reset by peer`.
By default are 3 threads.

**Comment by ronaldtse** [comment]
@andrew2net 

1. Can we limit the number of threads to 3 max?
2. Can we write to a new file for every field, every group and every subgroup? We don't want them all in the same file. 

Thanks!

**Comment by andrew2net** [comment]
@ronaldtse 
1. No problem.
2. So it will be about 1300 files. Right?

**Comment by ronaldtse** [comment]
2. If that's the case 👍

**Comment by andrew2net** [comment]
2. No problem

**Comment by andrew2net** [comment]
@ronaldtse done

**Comment by ronaldtse** [comment]
Excellent, thank you!

**Comment by ronaldtse** [comment]
@andrew2net could you also help specify the JSON-LD contexts, and generally polish the README of both repos? e.g., what is the data for, where we extracted it from, how to use it. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse I'm new in JSON-LD. What do you mean `specify the JSON-LD contexts`?
As I understand it needs to create API service which returns context description or includes the description to each file.

**Comment by ronaldtse** [comment]
The JSON-LD contexts are specified here already (https://github.com/riboseinc/iso-ics-codes-scripts/issues/1), just wanted you to check if they are correct.

The domain name is not existent yet.

**Comment by andrew2net** [comment]
@ronaldtse Yeah, I checked them with https://json-ld.org/playground/ service

**Comment by ronaldtse** [comment]
@andrew2net we've just registered the domain "standardn.com" ("Standard N", for "resources for and about standards", "N" stands for "many/any"). So we can make a simple GitHub site that links to that domain name, and hosts the `.jsonld` and `.json` files.

**Comment by andrew2net** [comment]
@ronaldtse Great! So we need to implement JSON-LD API for iso-ics-codes, do we?

**Comment by ronaldtse** [comment]
I don't think we actually need to make an API, but just placing static `jsonld` files at the right paths?

**Comment by andrew2net** [comment]
Yes indeed, it could be just static files.
